name: PaperWhitelist
version: '${project.version}'
main: cn.paper_card.whitelist.PluginMain
api-version: '1.20'
author: Paper99
folia-supported: true

depend:
  - Database

commands:
  whitelist:
    permission: paper-whitelist.command

permissions:
  paper-whitelist.command:
    default: op